apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-webhook-url: "https://hooks.slack.com/services/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"
