name: Build and Deploy Frontend & Backend

on:
  push:
    tags:
      - 'v*'  # Trigger pipeline เมื่อสร้าง tag ที่ขึ้นต้นด้วย v เช่น v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          repository: srbeam/frontend
          path: frontend

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: srbeam/backend
          path: backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract tag version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push backend image
        run: |
          docker build -t mysarisa/backend:${{ env.VERSION }} ./backend
          docker push mysarisa/backend:${{ env.VERSION }}

      - name: Build and push frontend image
        run: |
          docker build -t mysarisa/frontend:${{ env.VERSION }} ./frontend
          docker push mysarisa/frontend:${{ env.VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update backend image in ArgoCD manifests
        run: |
          sed -i "s|image: mysarisa/backend:.*|image: mysarisa/backend:${{ env.VERSION }}|" argocd/backend-app.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update backend image to version ${{ env.VERSION }}"
          git push

      - name: Update frontend image in ArgoCD manifests
        run: |
          sed -i "s|image: mysarisa/frontend:.*|image: mysarisa/frontend:${{ env.VERSION }}|" argocd/frontend-app.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update frontend image to version ${{ env.VERSION }}"
          git push
