name: Build and Push Docker Images to AWS ECR

on:
  push:
    tags:
      - "v*"  # Trigger pipeline เมื่อสร้าง tag ที่ขึ้นต้นด้วย v เช่น v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          repository: srbeam/frontend
          path: frontend

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: srbeam/backend
          path: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Build and Push Backend Image
      - name: Build and Push Backend Image to ECR
        env:
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_BACKEND }}
          VERSION: ${{ github.run_number }}
        run: |
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$VERSION ./backend
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$VERSION

      # Build and Push Frontend Image
      - name: Build and Push Frontend Image to ECR
        env:
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_FRONTEND }}
          VERSION: ${{ github.run_number }}
        run: |
          docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$VERSION ./frontend
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$VERSION
